# Generated by Django 6.0.6 on 2026-09-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosMesMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=7, unique=True)),
                ('ventas_netas', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unidades', models.IntegerField(default=0)),
                ('clientes_activos', models.IntegerField(default=0)),
                ('clientes_80', models.IntegerField(default=0)),
                ('productos_80', models.IntegerField(default=0)),
                ('observaciones', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CompraMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=7)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('documento', models.CharField(blank=True, default='', max_length=50)),
                ('proveedor', models.CharField(max_length=200)),
                ('producto', models.CharField(blank=True, default='', max_length=200)),
                ('descripcion', models.CharField(blank=True, default='', max_length=300)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rubro', models.CharField(choices=[('materia_prima', 'Materia prima e insumos directos'), ('sueldos_productivos', 'Sueldos productivos (incl. administrativos)'), ('administracion', 'Administración'), ('honorarios_direccion', 'Honorarios dirección'), ('gastos_fijos', 'Gastos fijos operativos'), ('logistica', 'Logística y distribución'), ('impuestos', 'Impuestos'), ('financieros', 'Financieros'), ('capex', 'Capex / Inversiones'), ('retiro_societario', 'Retiro societario / distribución de utilidades'), ('otro_excluir', 'Otro / gasto personal (excluir)'), ('sin_categorizar', 'Sin categorizar')], default='sin_categorizar', max_length=30)),
                ('xubio_transaccion_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['mes'], name='gestion_ger_mes_dd3b41_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReglaCategorizacionMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=200)),
                ('producto', models.CharField(blank=True, default='*', max_length=200)),
                ('rubro', models.CharField(choices=[('materia_prima', 'Materia prima e insumos directos'), ('sueldos_productivos', 'Sueldos productivos (incl. administrativos)'), ('administracion', 'Administración'), ('honorarios_direccion', 'Honorarios dirección'), ('gastos_fijos', 'Gastos fijos operativos'), ('logistica', 'Logística y distribución'), ('impuestos', 'Impuestos'), ('financieros', 'Financieros'), ('capex', 'Capex / Inversiones'), ('retiro_societario', 'Retiro societario / distribución de utilidades'), ('otro_excluir', 'Otro / gasto personal (excluir)'), ('sin_categorizar', 'Sin categorizar')], max_length=30)),
            ],
            options={
                'unique_together': {('proveedor', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='VentaClienteMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=7)),
                ('cliente', models.CharField(max_length=200)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['mes'], name='gestion_ger_mes_bd23a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='VentaProductoMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=7)),
                ('producto', models.CharField(max_length=200)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['mes'], name='gestion_ger_mes_91b939_idx')],
            },
        ),
    ]
