# Generated by Django 6.0.6 on 2026-09-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_gerencial', '0002_seed_reglas_mapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='compramapa',
            name='xubio_item_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
