# Generated by Django 6.0.6 on 2026-09-05 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_gerencial', '0003_compramapa_xubio_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCosteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldos_productivos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('horas_disponibles', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('margen_minimo', models.DecimalField(decimal_places=4, default=0.1, max_digits=6)),
                ('energia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mantenimiento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('limpieza', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sueldos_indirectos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('resto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aguinaldos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('alquiler', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('muni', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ganancias', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('contador', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='EquipoCosteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor_reposicion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vida_util_anios', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPrecioCosteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=200)),
                ('valor_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_nuevo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='InsumoCosteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('unidad', models.CharField(max_length=20)),
                ('precio', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('comentario', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoCosteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('familia', models.CharField(max_length=100)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precio_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_con_iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_distribuidor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidades_mes', models.IntegerField(default=0)),
                ('unidades_lote', models.IntegerField(default=0)),
                ('margen_objetivo', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('descuento_objetivo', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('xubio_producto_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotCosteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.CharField(blank=True, default='', max_length=300)),
                ('resumen', models.JSONField()),
                ('snapshot', models.JSONField()),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ManoObraCosteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.CharField(blank=True, default='', max_length=200)),
                ('personas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tiempo_min_lote', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mano_obra', to='gestion_gerencial.productocosteo')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaLineaCosteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, default='', max_length=50)),
                ('unidad', models.CharField(blank=True, default='', max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('merma', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_gerencial.insumocosteo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='gestion_gerencial.productocosteo')),
            ],
        ),
    ]
