# Generated by Django 6.0.6 on 2026-09-06 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_gerencial', '0006_seed_xubio_ids_costeo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCuentaEERR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('linea_eerr', models.CharField(choices=[('ingresos_netos', 'Ingresos netos'), ('cmv_stock', 'CMV / Stock'), ('cmv', 'CMV'), ('mano_obra_directa', 'Mano de obra directa'), ('gastos_variables', 'Gastos variables'), ('indirectos_productivos', 'Indirectos productivos'), ('amortizaciones', 'Amortizaciones'), ('gastos_administracion', 'Gastos administración'), ('impuestos', 'Impuestos'), ('gastos_financieros', 'Gastos financieros'), ('otros_resultados', 'Otros resultados'), ('no_eerr', 'No EERR')], max_length=30)),
                ('rubro', models.CharField(blank=True, default='', max_length=100)),
                ('incluir_eerr', models.BooleanField(default=True)),
                ('signo', models.SmallIntegerField(default=1)),
                ('descripcion', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VentaProductoEERR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=7)),
                ('fecha', models.DateField()),
                ('xubio_producto_id', models.IntegerField(blank=True, null=True)),
                ('producto', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField(default=0)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'indexes': [models.Index(fields=['mes'], name='gestion_ger_mes_172b34_idx'), models.Index(fields=['fecha'], name='gestion_ger_fecha_007699_idx')],
            },
        ),
        migrations.CreateModel(
            name='XubioProductoCosteoMapeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xubio_producto_id', models.IntegerField(unique=True)),
                ('xubio_producto_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('producto_costeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeos_xubio', to='gestion_gerencial.productocosteo')),
            ],
        ),
        migrations.CreateModel(
            name='CompraEERR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=7)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('documento', models.CharField(blank=True, default='', max_length=50)),
                ('proveedor', models.CharField(max_length=200)),
                ('producto', models.CharField(blank=True, default='', max_length=200)),
                ('descripcion', models.CharField(blank=True, default='', max_length=300)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('xubio_transaccion_id', models.BigIntegerField(blank=True, null=True)),
                ('xubio_item_id', models.BigIntegerField(blank=True, null=True)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_gerencial.plancuentaeerr')),
            ],
            options={
                'indexes': [models.Index(fields=['mes'], name='gestion_ger_mes_35ef7d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReglaAsignacionCuentaEERR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=200)),
                ('producto', models.CharField(blank=True, default='*', max_length=200)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_gerencial.plancuentaeerr')),
            ],
            options={
                'unique_together': {('proveedor', 'producto')},
            },
        ),
    ]
