# Generated by Django 6.0.6 on 2026-09-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_gerencial', '0009_snapshotcosteo_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCorrienteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente (a cobrar)'), ('proveedor', 'Proveedor (a pagar)')], max_length=10)),
                ('contraparte', models.CharField(max_length=150)),
                ('comprobante', models.CharField(blank=True, max_length=60)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(db_index=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('cancelado', 'Cobrado / pagado')], db_index=True, default='pendiente', max_length=10)),
                ('fecha_cancelacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=300)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('import', 'Importado'), ('xubio', 'Xubio')], default='manual', max_length=10)),
                ('external_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuenta corriente (comprobante)',
                'ordering': ['fecha_vencimiento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SaldoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(choices=[('bbva', 'BBVA'), ('mercado_pago', 'Mercado Pago')], max_length=20)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Saldo bancario',
                'ordering': ['-fecha', 'cuenta'],
                'unique_together': {('cuenta', 'fecha')},
            },
        ),
    ]
