# Generated by Django 6.0.6 on 2026-09-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_gerencial', '0010_cuentacorrienteitem_saldobancario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoEERR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True)),
                ('ventas_mes_inicial', models.DecimalField(decimal_places=2, max_digits=14)),
                ('crecimiento_ventas', models.DecimalField(decimal_places=4, max_digits=6)),
                ('cmv_pct', models.DecimalField(decimal_places=4, max_digits=6)),
                ('gastos_variables_pct', models.DecimalField(decimal_places=4, max_digits=6)),
                ('gastos_financieros_pct', models.DecimalField(decimal_places=4, max_digits=6)),
                ('impuestos_pct', models.DecimalField(decimal_places=4, max_digits=6)),
                ('mo_directa_base', models.DecimalField(decimal_places=2, max_digits=14)),
                ('indirectos_base', models.DecimalField(decimal_places=2, max_digits=14)),
                ('administracion_base', models.DecimalField(decimal_places=2, max_digits=14)),
                ('incremento_estructura', models.DecimalField(decimal_places=4, max_digits=6)),
                ('amortizaciones_mensuales', models.DecimalField(decimal_places=2, max_digits=14)),
                ('resultado_objetivo_pct', models.DecimalField(decimal_places=4, max_digits=6)),
                ('tolerancia_ingresos', models.DecimalField(decimal_places=4, default=0.9, max_digits=6)),
                ('tolerancia_egresos', models.DecimalField(decimal_places=4, default=1.1, max_digits=6)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Presupuesto EERR',
                'ordering': ['-anio'],
            },
        ),
    ]
