# Generated by Django 6.0.6 on 2026-09-26 15:31

from django.db import migrations, models

NOMBRES_INICIALES = {
    'nataliacarnero': 'Nati',
    'matiloinsta': 'Mati',
}


def cargar_nombres(apps, schema_editor):
    Perfil = apps.get_model('users', 'Perfil')
    for username, nombre in NOMBRES_INICIALES.items():
        Perfil.objects.filter(usuario__username=username, nombre='').update(nombre=nombre)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(blank=True, help_text='Cómo se muestra en el panel, ej: "Mati".', max_length=50),
        ),
        migrations.RunPython(cargar_nombres, migrations.RunPython.noop),
    ]
