# Generated by Django 6.0.6 on 2026-09-26 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('mensaje', models.CharField(blank=True, max_length=300)),
                ('url', models.CharField(blank=True, help_text='Adónde lleva al hacer clic (opcional).', max_length=300)),
                ('icono', models.CharField(default='ti-bell', help_text='Nombre de ícono de Tabler, ej: ti-clipboard-list.', max_length=50)),
                ('nivel', models.CharField(choices=[('info', 'Información'), ('exito', 'Éxito'), ('alerta', 'Alerta'), ('error', 'Error')], default='info', max_length=10)),
                ('modulo', models.CharField(blank=True, help_text='Módulo que la generó, ej: pedidos.', max_length=50)),
                ('rol', models.CharField(blank=True, help_text='Si se completa, sólo la ven los usuarios con este rol.', max_length=50)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('leida_por', models.ManyToManyField(blank=True, related_name='notificaciones_leidas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, help_text='Si se completa, sólo la ve este usuario.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-creada'],
            },
        ),
    ]
