# Generated by Django 6.0.6 on 2026-07-04 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ListaPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tamaño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_medida', models.CharField(choices=[('diametro', 'Diámetro'), ('largo_ancho', 'Largo x Ancho'), ('largo_ancho_alto', 'Largo x Ancho x Alto')], max_length=20)),
                ('medida_1', models.DecimalField(decimal_places=1, max_digits=6)),
                ('medida_2', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('medida_3', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('unidades_paquete', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lista_precios.familia')),
                ('tamaño', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lista_precios.tamaño')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lista_precios.variedad')),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lista_precios.listaprecios')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lista_precios.producto')),
            ],
        ),
        migrations.AddField(
            model_name='listaprecios',
            name='tipo_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lista_precios.tipocliente'),
        ),
    ]
