# Generated by Django 6.0.6 on 2026-07-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_precios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaprecios',
            name='fecha',
            field=models.DateField(),
        ),
    ]
