# Generated by Django 6.0.6 on 2026-07-04 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista_precios', '0002_alter_listaprecios_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaprecios',
            name='activo',
        ),
    ]
