# Generated by Django 6.0.6 on 2026-07-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista_precios', '0003_remove_listaprecios_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaprecios',
            name='tipo_cliente',
        ),
    ]
