# Generated by Django 6.0.6 on 2026-07-23 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_precios', '0004_remove_listaprecios_tipo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaprecios',
            name='tipo_cliente',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='lista_precios.tipocliente'),
            preserve_default=False,
        ),
    ]
