# Generated by Django 6.0.6 on 2026-08-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_precios', '0005_listaprecios_tipo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='xubio_producto_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
