# Generated by Django 6.0.6 on 2026-08-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_precios', '0006_producto_xubio_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='medida_1',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
