# Generated by Django 6.0.6 on 2026-08-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_precios', '0007_alter_producto_medida_1'),
        ('sistema_pedidos', '0008_cliente_permite_domicilio_cliente_permite_retiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='clientes_exclusivos',
            field=models.ManyToManyField(blank=True, related_name='productos_exclusivos', to='sistema_pedidos.cliente'),
        ),
    ]
