# Generated by Django 6.0.6 on 2026-08-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_precios', '0008_producto_clientes_exclusivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaprecios',
            name='pdf_catalogo',
            field=models.FileField(blank=True, null=True, upload_to='catalogos/'),
        ),
    ]
