# Generated by Django 6.0.6 on 2026-08-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_precios', '0009_listaprecios_pdf_catalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
