# Generated by Django 6.0.6 on 2026-09-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_precios', '0010_alter_precio_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaprecios',
            name='xubio_lista_precio_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
