# Generated by Django 6.0.6 on 2026-09-01 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_precios', '0011_listaprecios_xubio_lista_precio_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaprecios',
            name='tipo_cliente',
        ),
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='lista_precios.listaprecios')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='lista_precios.producto')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
