# Generated by Django 6.0.6 on 2026-09-21 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_precios', '0012_remove_listaprecios_tipo_cliente_historialprecio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente_desde', models.DateTimeField()),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('aplicada', 'Aplicada'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('aplicada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizaciones', to='lista_precios.listaprecios')),
            ],
            options={
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='ItemActualizacionPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lista_precios.actualizacionprecios')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lista_precios.producto')),
            ],
        ),
        migrations.AddConstraint(
            model_name='actualizacionprecios',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'programada')), fields=('lista_precio',), name='una_programada_por_lista'),
        ),
        migrations.AlterUniqueTogether(
            name='itemactualizacionprecios',
            unique_together={('actualizacion', 'producto')},
        ),
    ]
