# Generated by Django 6.0.6 on 2026-07-08 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lista_precios', '0003_remove_listaprecios_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('razon_social', models.CharField(max_length=50)),
                ('cuit', models.CharField(max_length=13)),
                ('nombre_comercio', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254)),
                ('condicion_iva', models.CharField(choices=[('responsable_incripto', 'Responsable Inscripto'), ('monotributista', 'Monotributista'), ('consumidor_final', 'Consumidor Final')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('token', models.CharField(max_length=100)),
                ('token_expiracion', models.DateTimeField()),
                ('tipo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lista_precios.tipocliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='nuevo', max_length=50)),
                ('metodo_entrega', models.CharField(choices=[('retiro', 'Retiro en Fabrica'), ('entrega_domicilio', 'Entrega en Domicilio')], max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema_pedidos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lista_precios.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pedidos.pedido')),
            ],
        ),
    ]
