# Generated by Django 6.0.6 on 2026-07-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='token_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
