# Generated by Django 6.0.6 on 2026-07-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0002_alter_cliente_token_alter_cliente_token_expiracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='posee_deuda',
            field=models.BooleanField(default=False),
        ),
    ]
