# Generated by Django 6.0.6 on 2026-07-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0003_cliente_posee_deuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='condicion_iva',
            field=models.CharField(choices=[('responsable_inscripto', 'Responsable Inscripto'), ('monotributista', 'Monotributista'), ('consumidor_final', 'Consumidor Final')], max_length=50),
        ),
    ]
