# Generated by Django 6.0.6 on 2026-07-23 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_precios', '0005_listaprecios_tipo_cliente'),
        ('sistema_pedidos', '0004_alter_cliente_condicion_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='lista_precios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lista_precios.listaprecios'),
        ),
    ]
