# Generated by Django 6.0.6 on 2026-07-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0005_cliente_lista_precios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
