# Generated by Django 6.0.6 on 2026-08-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0006_pedido_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dias_cc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='xubio_cliente_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='xubio_punto_venta_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='xubio_tipo_comprobante',
            field=models.IntegerField(blank=True, choices=[(1, 'Factura'), (6, 'Recibo')], null=True),
        ),
    ]
