# Generated by Django 6.0.6 on 2026-08-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0007_cliente_dias_cc_cliente_xubio_cliente_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='permite_domicilio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='permite_retiro',
            field=models.BooleanField(default=True),
        ),
    ]
