# Generated by Django 6.0.6 on 2026-08-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0008_cliente_permite_domicilio_cliente_permite_retiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
