# Generated by Django 6.0.6 on 2026-08-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0009_alter_itempedido_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xubio_producto_id', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('stock_actual', models.IntegerField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
