# Generated by Django 6.0.6 on 2026-09-23 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_precios', '0013_actualizacionprecios_itemactualizacionprecios_and_more'),
        ('sistema_pedidos', '0010_stockproducto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('mensaje', models.TextField()),
                ('origen', models.CharField(choices=[('lista_precios', 'Nueva lista de precios'), ('manual', 'Comunicación general')], max_length=20)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones', to='lista_precios.actualizacionprecios')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='ComunicacionDestinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('mail_enviado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones', to='sistema_pedidos.cliente')),
                ('comunicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='sistema_pedidos.comunicacion')),
            ],
            options={
                'unique_together': {('comunicacion', 'cliente')},
            },
        ),
    ]
