# Generated by Django 6.0.6 on 2026-09-15 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('efectivo_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.CharField(blank=True, max_length=300)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre diario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('cobro_ventas', 'Cobro ventas'), ('pago_proveedor', 'Pago proveedor'), ('otro_egreso', 'Otro egreso'), ('otro_ingreso', 'Otro ingreso'), ('gasto_caja_chica', 'Gasto caja chica'), ('sueldo_jornal', 'Sueldo/Jornal')], max_length=30)),
                ('cliente_proveedor', models.CharField(blank=True, max_length=100)),
                ('detalle', models.CharField(blank=True, max_length=200)),
                ('nro_comprobante', models.CharField(blank=True, max_length=50)),
                ('nro_recibo_op', models.CharField(blank=True, max_length=50)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('conciliado', models.BooleanField(default=False)),
                ('observaciones', models.CharField(blank=True, max_length=300)),
                ('estado', models.CharField(choices=[('parcial', 'Parcial'), ('completo', 'Completo'), ('bloqueado', 'Bloqueado')], default='parcial', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConciliacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importacion_fecha', models.DateField(auto_now_add=True)),
                ('fecha_xubio', models.DateField()),
                ('nro_comprobante_xubio', models.CharField(max_length=50)),
                ('cliente_xubio', models.CharField(max_length=100)),
                ('importe_xubio', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('ok', 'OK'), ('falta_en_caja', 'Falta en caja'), ('monto_difiere', 'Monto difiere'), ('falta_en_xubio', 'Falta en Xubio')], max_length=20)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('movimiento_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_caja.movimientocaja')),
            ],
            options={
                'verbose_name': 'Item de conciliación',
                'ordering': ['-importacion_fecha', 'fecha_xubio'],
            },
        ),
        migrations.CreateModel(
            name='SaldoInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saldo inicial',
            },
        ),
    ]
