# Generated by Django 6.0.6 on 2026-09-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_horario', '0002_seed_datos_historicos'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='marcafichada',
            new_name='control_hor_mes_6e58ef_idx',
            old_name='control_hor_mes_marcas_idx',
        ),
        migrations.RenameIndex(
            model_name='marcafichada',
            new_name='control_hor_emplead_e8ed38_idx',
            old_name='control_hor_emp_mes_idx',
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre_reloj',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
    ]
