# Generated by Django 6.0.6 on 2026-09-26 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_horario', '0003_rename_control_hor_mes_marcas_idx_control_hor_mes_6e58ef_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_incidencias_mes', models.PositiveIntegerField(default=3, help_text='Cantidad de rectificaciones en un mes a partir de la cual se sugiere evaluar un apercibimiento.')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='dni',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sector_turno',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='RectificacionFichada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de la incidencia')),
                ('estado', models.CharField(choices=[('pendiente_firma', 'Pendiente de firma y foto'), ('pendiente_resolucion', 'Pendiente de resolución'), ('resuelta', 'Resuelta'), ('anulada', 'Anulada')], default='pendiente_firma', max_length=25)),
                ('dni', models.CharField(blank=True, default='', max_length=15)),
                ('sector_turno', models.CharField(blank=True, default='', max_length=100)),
                ('tipos', models.JSONField(default=list, help_text='Lista de tipos de incidencia')),
                ('tipo_otro', models.CharField(blank=True, default='', max_length=120)),
                ('marcas_originales', models.CharField(blank=True, default='', help_text='Copia de las marcas del reloj al momento del pedido', max_length=300)),
                ('calculo_provisional', models.CharField(blank=True, default='', max_length=300)),
                ('horas_provisionales', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('real_entrada', models.TimeField(blank=True, null=True)),
                ('real_salida_descanso', models.TimeField(blank=True, null=True)),
                ('real_regreso_descanso', models.TimeField(blank=True, null=True)),
                ('real_salida', models.TimeField(blank=True, null=True)),
                ('sin_descanso_declarado', models.BooleanField(default=False, help_text='El trabajador declara que no pudo tomar el descanso')),
                ('horario_real_texto', models.CharField(blank=True, default='', max_length=300)),
                ('motivo', models.TextField()),
                ('fecha_hora_aviso', models.DateTimeField()),
                ('medio_aviso', models.CharField(blank=True, default='Formulario entregado al responsable designado.', max_length=200)),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='control_horario/rectificaciones/')),
                ('foto_subida_el', models.DateTimeField(blank=True, null=True)),
                ('verif_biometrico', models.BooleanField(blank=True, null=True)),
                ('verif_horario_programado', models.BooleanField(blank=True, null=True)),
                ('verif_camaras', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('no_disponibles', 'No disponibles')], default='', max_length=15)),
                ('verif_registros', models.BooleanField(blank=True, null=True)),
                ('verif_supervisor', models.BooleanField(blank=True, null=True)),
                ('verif_otros', models.TextField(blank=True, default='')),
                ('resolucion', models.CharField(blank=True, choices=[('acreditada', 'Incidencia acreditada: se autoriza corrección excepcional'), ('parcial', 'Incidencia parcialmente acreditada: se autoriza corrección por el horario comprobado'), ('no_acreditada', 'Incidencia no acreditada: se mantiene el cálculo administrativo provisional')], default='', max_length=15)),
                ('horario_corregido', models.CharField(blank=True, default='', max_length=200)),
                ('horas_a_liquidar', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('aprobado_por', models.CharField(blank=True, default='', help_text='Responsable que firmó la resolución en papel', max_length=150)),
                ('resuelta_el', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.CharField(blank=True, default='', max_length=300)),
                ('anulada_el', models.DateTimeField(blank=True, null=True)),
                ('anulada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rectificaciones', to='control_horario.empleado')),
                ('foto_subida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['empleado', 'fecha'], name='control_hor_emplead_914134_idx')],
            },
        ),
    ]
