# Generated by Django 6.0.6 on 2026-09-26 18:18

import django.db.models.deletion
from django.db import migrations, models


def vincular(apps, schema_editor):
    from control_horario.legajos_link import vincular_automaticamente
    vincular_automaticamente(apps.get_model('control_horario', 'Empleado'), apps.get_model('legajos', 'Empleado'))


class Migration(migrations.Migration):

    dependencies = [
        ('control_horario', '0004_rectificaciones'),
        ('legajos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='legajo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado_reloj', to='legajos.empleado'),
        ),
        migrations.RunPython(vincular, migrations.RunPython.noop),
    ]
