# Generated by Django 6.0.6 on 2026-09-17 18:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('documentacion_vencimiento', 'Vencimiento de documentación'), ('cumpleanios', 'Cumpleaños')], max_length=30)),
                ('referencia_id', models.PositiveIntegerField(help_text='ID de DocumentacionEmpleado o Empleado')),
                ('fecha_aviso', models.DateField(help_text="Fecha 'lógica' del aviso: hoy o 7 días antes")),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('tipo', 'referencia_id', 'fecha_aviso')},
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('cuil', models.CharField(blank=True, max_length=15)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='legajos/empleados/fotos/')),
                ('puesto', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('legajo_inicial', 'Legajo inicial'), ('apercibimiento', 'Apercibimiento'), ('cambio_domicilio', 'Cambio de domicilio'), ('comunicado', 'Comunicado interno'), ('constancia_trabajo', 'Constancia de trabajo'), ('suspension', 'Suspensión'), ('otro', 'Otro')], max_length=30)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('motivo', models.TextField(blank=True, help_text='Detalle que completa el admin; se usa para armar el texto a imprimir')),
                ('domicilio_nuevo', models.CharField(blank=True, help_text="Solo para tipo 'Cambio de domicilio'", max_length=255)),
                ('pdf_generado', models.FileField(blank=True, null=True, upload_to='legajos/documentos/generados/')),
                ('archivo_firmado', models.FileField(blank=True, null=True, upload_to='legajos/documentos/firmados/')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('generado', 'Generado, pendiente de firma'), ('firmado', 'Firmado')], default='borrador', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('firmado_en', models.DateField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='legajos.empleado')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DocumentacionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('carnet_manipulacion', 'Carnet de manipulación de alimentos'), ('credencial_art', 'Credencial ART'), ('otro', 'Otro')], max_length=30)),
                ('tipo_otro_detalle', models.CharField(blank=True, help_text="Completar solo si el tipo es 'Otro'", max_length=100)),
                ('archivo', models.FileField(upload_to='legajos/documentacion/')),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentacion', to='legajos.empleado')),
            ],
            options={
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('tipo', models.CharField(choices=[('enfermedad', 'Enfermedad'), ('personal', 'Personal'), ('injustificada', 'Injustificada'), ('vacaciones', 'Vacaciones'), ('art', 'Accidente / ART'), ('otra', 'Otra')], max_length=20)),
                ('justificada', models.BooleanField(default=False)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='legajos/ausencias/')),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to='legajos.empleado')),
            ],
            options={
                'ordering': ['-fecha_desde'],
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo', models.CharField(choices=[('aviso', 'Aviso'), ('cambio', 'Cambio'), ('felicitacion', 'Felicitación'), ('otra', 'Otra')], default='aviso', max_length=20)),
                ('texto', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(blank=True, help_text='Vacío = novedad general para todo el equipo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='legajos.empleado')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
